const ASSETS = [
    'Samba Dancing',
    'morph_test',
    'monkey',
    'monkey_embedded_texture',
    'vCube',
    'archer/ArcherRi01',
    'warrior/Warrior',
    'stanford-bunny',
    'mixamo',
    'RotationTest',
    'exampleWindow',
    'Head_69',
    'morph-translation',
    // Unit-test assets generated by tools/blender/
    'test/anim_euler_jump',
    'test/anim_skin_bend',
    'test/anim_root_motion',
    // glTF sample models converted to FBX
    'gltf/AnimatedTriangle',
    'gltf/RiggedSimple',
    'gltf/RiggedFigure',
    'gltf/Fox',
];

const SCALES = new Map([
    ['warrior/Warrior',    100],
    ['archer/ArcherRi01',  100],
    ['stanford-bunny',     0.001],
    ['Head_69',            100],
    ['gltf/Fox',           0.01],
]);

const FBX_BASE = '../../assets/models/fbx/';
const CUSTOM_URL_OPTION = '__custom_url__';
const SEARCH_PARAMS = new URLSearchParams(window.location.search);

let engine, scene, canvas, camera;
let importedMeshes = [];
let gui, assetController, animationFolder, morphsFolder, timeController;
let activeAnimations = [];
let allClips = []; // [{ name, controls }]
let isLoading = false;
let shadowGenerator = null;

function setStatus(msg) {
    document.getElementById('status').textContent = msg;
}

function getInitialModel() {
    const model = SEARCH_PARAMS.get('model');
    return ASSETS.includes(model) ? model : 'vCube';
}

function getCustomUrl() {
    const url = SEARCH_PARAMS.get('url');
    return url && url.trim() ? url.trim() : null;
}

function getInitialSelection() {
    return getCustomUrl() ? CUSTOM_URL_OPTION : getInitialModel();
}

function getAssetOptions() {
    const options = {};
    const customUrl = getCustomUrl();
    if (customUrl) options[`Custom: ${getUrlFileName(customUrl)}`] = CUSTOM_URL_OPTION;
    ASSETS.forEach(name => {
        options[name] = name;
    });
    return options;
}

function getUrlFileName(url) {
    try {
        const parsed = new URL(url, window.location.href);
        const name = parsed.pathname.split('/').pop() || url;
        return decodeURIComponent(name);
    } catch {
        const name = url.split(/[\\/]/).pop() || url;
        return decodeURIComponent(name);
    }
}

function getScaleOverride() {
    const scale = Number(SEARCH_PARAMS.get('scale'));
    return Number.isFinite(scale) && scale > 0 ? scale : null;
}

function getAnimationEnabled() {
    const value = SEARCH_PARAMS.get('animation') ?? SEARCH_PARAMS.get('anim');
    return !['0', 'false', 'off', 'no'].includes((value ?? '').toLowerCase());
}

function getAnimationTime() {
    const value = SEARCH_PARAMS.get('time');
    const time = value === null ? NaN : Number(value);
    return Number.isFinite(time) ? time : null;
}

function getInitialClipName() {
    return SEARCH_PARAMS.get('clip') ?? null;
}

const PARAMS = {
    asset: getInitialSelection(),
    animate: getAnimationEnabled(),
    clip: '',
    time: getAnimationTime() ?? 0,
    debug: showDebugLayer,
};

function frameModel(nodes) {
    const meshes = nodes.filter(node => node instanceof BABYLON.Mesh);
    if (!meshes.length) return;

    let min = null;
    let max = null;
    for (const mesh of meshes) {
        mesh.computeWorldMatrix(true);
        const bounds = mesh.getBoundingInfo().boundingBox;
        const bMin = bounds.minimumWorld;
        const bMax = bounds.maximumWorld;
        min = min
            ? BABYLON.Vector3.Minimize(min, bMin)
            : bMin.clone();
        max = max
            ? BABYLON.Vector3.Maximize(max, bMax)
            : bMax.clone();
    }

    const center = min.add(max).scale(0.5);
    const size = max.subtract(min).length();
    camera.target.copyFrom(center);
    camera.radius = Math.max(size * 1.25, 1);
}

async function loadModel(selection) {
    if (isLoading) return;
    isLoading = true;
    const customUrl = selection === CUSTOM_URL_OPTION ? getCustomUrl() : null;
    const name = customUrl ? getUrlFileName(customUrl).replace(/\.fbx$/i, '') : selection;
    setStatus(`読み込み中: ${name} ...`);

    try {
        importedMeshes.forEach(m => m.dispose());
        importedMeshes = [];
        activeAnimations = [];
        allClips = [];
        rebuildAnimationFolder();

        const url = customUrl ?? (FBX_BASE + selection.split('/').map(encodeURIComponent).join('/') + '.fbx');

        const meshes = await FBXLoader.loadFBX(url, scene, {
            animation: getAnimationEnabled(),
            animationTime: getAnimationTime(),
        });

        const scale = getScaleOverride() ?? SCALES.get(selection) ?? 1;
        if (scale !== 1) {
            // Only scale root nodes; children inherit scale through the hierarchy.
            meshes.filter(m => !meshes.includes(m.parent)).forEach(m => m.scaling.scaleInPlace(scale));
        }

        importedMeshes = meshes;
        if (shadowGenerator) {
            meshes.filter(m => m instanceof BABYLON.Mesh).forEach(m => {
                shadowGenerator.addShadowCaster(m);
                m.receiveShadows = true;
            });
        }
        PARAMS.asset = selection;
        rebuildAnimationFolder();
        rebuildMorphsFolder();

        const meshCount = meshes.filter(m => m instanceof BABYLON.Mesh).length;
        const msg = `${name} — meshes: ${meshCount}`;
        console.log(msg);
        setStatus(msg);

    } catch (err) {
        console.error(err);
        setStatus(`エラー: ${err.message}`);
    } finally {
        isLoading = false;
    }
}

function getAnimationClips() {
    const clips = [];
    importedMeshes.forEach(node => {
        const nodeClips = node.metadata?.fbxAnimationClips;
        if (Array.isArray(nodeClips)) clips.push(...nodeClips);
    });
    return clips;
}

function buildTimeController(duration) {
    if (timeController) timeController.destroy();
    timeController = animationFolder.add(PARAMS, 'time', 0, duration, 0.01)
        .name('time')
        .onChange(value => {
            activeAnimations.forEach(ctrl => ctrl.setTime(value));
        });
}

function switchToClip(clip) {
    activeAnimations.forEach(ctrl => ctrl.setPlaying(false));
    activeAnimations = clip.controls;
    const duration = Math.max(...activeAnimations.map(ctrl => ctrl.duration), 0);
    PARAMS.time = 0;
    buildTimeController(duration);
    activeAnimations.forEach(ctrl => {
        ctrl.setTime(0);
        ctrl.setPlaying(PARAMS.animate);
    });
    timeController.updateDisplay();
}

function rebuildMorphsFolder() {
    [...morphsFolder.children].forEach(child => child.destroy());
    morphsFolder.hide();

    let hasAnyTarget = false;
    for (const node of importedMeshes) {
        const mgr = node?.morphTargetManager;
        if (!mgr || mgr.numTargets === 0) continue;
        hasAnyTarget = true;
        const meshFolder = morphsFolder.addFolder(node.name || `mesh`);
        for (let i = 0; i < mgr.numTargets; i++) {
            const target = mgr.getTarget(i);
            meshFolder.add(target, 'influence', 0, 1, 0.01).name(target.name);
        }
    }
    if (hasAnyTarget) morphsFolder.show();
}

function rebuildAnimationFolder() {
    [...animationFolder.children].forEach(child => child.destroy());
    animationFolder.hide();
    timeController = null;

    allClips = getAnimationClips();
    if (!allClips.length) return;

    animationFolder.show();

    const initialClipName = getInitialClipName();
    const initialClip = (initialClipName ? allClips.find(c => c.name === initialClipName) : null) ?? allClips[0];

    if (allClips.length > 1) {
        const clipOptions = {};
        allClips.forEach(clip => { clipOptions[clip.name] = clip.name; });
        PARAMS.clip = initialClip.name;
        animationFolder.add(PARAMS, 'clip', clipOptions).name('clip')
            .onChange(clipName => {
                const clip = allClips.find(c => c.name === clipName);
                if (clip) switchToClip(clip);
            });
    }

    activeAnimations = initialClip.controls;
    PARAMS.animate = getAnimationEnabled();
    PARAMS.time = getAnimationTime() ?? 0;
    activeAnimations.forEach(ctrl => ctrl.setPlaying(PARAMS.animate));

    animationFolder.add(PARAMS, 'animate').name('play').onChange(value => {
        activeAnimations.forEach(ctrl => ctrl.setPlaying(value));
    });

    const duration = Math.max(...activeAnimations.map(ctrl => ctrl.duration), 0);
    buildTimeController(duration);
    activeAnimations.forEach(ctrl => ctrl.setTime(PARAMS.time));
    timeController.updateDisplay();
}

function showDebugLayer() {
    if (!scene?.debugLayer) return;
    if (scene.debugLayer.isVisible?.()) {
        scene.debugLayer.hide();
        return;
    }

    scene.debugLayer.show({
        embedMode: true,
        overlay: true,
        handleResize: false,
    });
}

function initGui() {
    gui = new lil.GUI();
    assetController = gui.add(PARAMS, 'asset', getAssetOptions()).name('asset');
    animationFolder = gui.addFolder('Animation').hide();
    morphsFolder = gui.addFolder('Morphs').hide();
    gui.add(PARAMS, 'debug').name('Debug');
}

async function init() {
    canvas = document.querySelector('#c');
    engine = new BABYLON.Engine(canvas, true);

    scene = new BABYLON.Scene(engine);
    scene.clearColor = new BABYLON.Color4(0.627, 0.627, 0.627, 1);
    scene.fogMode = BABYLON.Scene.FOGMODE_LINEAR;
    scene.fogColor = new BABYLON.Color3(0.627, 0.627, 0.627);
    scene.fogStart = 200;
    scene.fogEnd = 1000;

    // Match Three.js: camera at (100,200,300), target (0,100,0).
    // Babylon.js is LH so Z is negated → BJS camera at (100,200,-300).
    const _camTarget = new BABYLON.Vector3(0, 100, 0);
    const _camOffset = new BABYLON.Vector3(100, 100, -300); // pos - target
    const _camRadius = _camOffset.length();
    camera = new BABYLON.ArcRotateCamera(
        'camera',
        Math.atan2(_camOffset.z, _camOffset.x), // alpha
        Math.acos(_camOffset.y / _camRadius),    // beta
        _camRadius,
        _camTarget,
        scene
    );
    camera.attachControl(canvas, true);
    camera.wheelPrecision = 1;
    camera.lowerRadiusLimit = 1;
    camera.upperRadiusLimit = 2000;

    const hemi = new BABYLON.HemisphericLight('hemi', new BABYLON.Vector3(0, 1, 0), scene);
    hemi.groundColor = new BABYLON.Color3(0.267, 0.267, 0.267);
    hemi.intensity = 1.0;
    const dir = new BABYLON.DirectionalLight('dir', new BABYLON.Vector3(0, -2, 1), scene);
    dir.position = new BABYLON.Vector3(0, 200, -100);
    dir.intensity = 1.0;

    scene.environmentTexture = new BABYLON.CubeTexture(
        'https://cx20.github.io/gltf-test/textures/env/papermillSpecularHDR.env',
        scene
    );

    scene.imageProcessingConfiguration.toneMappingEnabled = true;
    scene.imageProcessingConfiguration.toneMappingType = BABYLON.ImageProcessingConfiguration.TONEMAPPING_KHR_PBR_NEUTRAL;
    scene.imageProcessingConfiguration.exposure = 1 / 0.6 * 1.5; // ≈ 2.5: compensates for lower light intensity vs Three.js

    const ground = BABYLON.MeshBuilder.CreateGround('ground', { width: 2000, height: 2000 }, scene);
    const groundMat = new BABYLON.StandardMaterial('groundMat', scene);
    groundMat.diffuseColor = new BABYLON.Color3(0.6, 0.6, 0.6);
    groundMat.specularColor = new BABYLON.Color3(0, 0, 0);
    groundMat.backFaceCulling = false;
    groundMat.alpha = 0.8;
    groundMat.disableDepthWrite = true;
    ground.material = groundMat;
    ground.receiveShadows = true;

    shadowGenerator = new BABYLON.ShadowGenerator(1024, dir);
    shadowGenerator.useBlurExponentialShadowMap = true;

    (function createGrid() {
        const size = 2000;
        const divisions = 20;
        const step = size / divisions;
        const half = size / 2;
        const lines = [];
        for (let i = 0; i <= divisions; i++) {
            const p = -half + i * step;
            lines.push([new BABYLON.Vector3(-half, 0, p), new BABYLON.Vector3(half, 0, p)]);
            lines.push([new BABYLON.Vector3(p, 0, -half), new BABYLON.Vector3(p, 0, half)]);
        }
        const grid = BABYLON.MeshBuilder.CreateLineSystem('grid', { lines }, scene);
        grid.color = new BABYLON.Color3(0, 0, 0);
        grid.alpha = 0.2;
    })();

    const initialSelection = getInitialSelection();
    initGui();

    engine.runRenderLoop(() => scene.render());
    window.addEventListener('resize', () => engine.resize());

    // 初期モデルを読み込む
    await loadModel(initialSelection);
    // Attach onChange only after the initial load so a browser-triggered
    // 'change' event during GUI setup cannot preempt the initial load.
    assetController.onChange(loadModel);
}

init();
